### ISSUE TITLE
"Known Issues" NMR Example Render does not Match Render at the top of Readme

### ISSUE THREAD

**Issue by KTMorton** [stelzner/srt#2]
At the beginning of the Readme the rendered rotation video from the NMR dataset is as follows:
<img src="https://drive.google.com/uc?id=1K1hX4jc50tVc1sCLacPT0p8SjWjkcRgv" alt="NMR Rotation" width="256"/>

However, later in the Readme you express that overfitting on the 24 input views is a "known issue". As such, is there a different configuration that you used to fix the overfitting issue and render the video above? Also, given that the authors checked over the codebase, do they know about the existence of this overfitting issue and did they provide any insight on how to mitigate it?

Known Issue video:
<img src="https://drive.google.com/uc?id=1ps9txhEghQOg1nADskt-3ok7umUQ9-jr" alt="NMR Camera Overfitting" width="512"/>

**Comment by stelzner** [comment]
Hi! SRT differs from NeRF-based in models in that it has no structural constraints guaranteeing geometric consistency between views. I think we can generally not expect such models to generalize to out-of-distribution cameras when the set of seen cameras is so small. I chatted with the authors about this, they also encountered the issue and agreed with this assessment.

So I don't think there's an easy fix for this, other than switching to a NeRF decoder (VSRT). The video above is the same as the video on the bottom left, it's simply the 24 known input views where SRT works. The video on the bottom right is from the same model, but here the camera smoothly rotates around the object as opposed to sticking to the 24 known views. Only when it passes one of the known views do we get a reasonable image.

**Comment by KTMorton** [comment]
Ok thank you so much for your reply! I thought that it might just be a general architecture/idea issue but I wanted to make sure as I did not see the authors mention it in their paper or on their website. I appreciate the insights and quick response!
