### ISSUE TITLE
Multishapenet dataset issue

### ISSUE THREAD

**Issue by junkeun-yi** [stelzner/srt#3]
Hello, loading the msn data raises a `typeError: type uint8 not recognized` dialogue. Was the dataset updated since the repository was made, or is there a modification needed?

**Comment by stelzner** [comment]
Hi, looking at the Google Cloud bucket, it doesn't seem like there are any changes: https://console.cloud.google.com/storage/browser/kubric-public/tfds/multi_shapenet_frames/2.3.3

Could you double check that you have the data arranged in the directory structure specified in the readme? If the problem persists, maybe you can share what exactly you did to set it up.
