### ISSUE TITLE
Extrinsic/Intrisic Camera Input

### ISSUE THREAD

**Issue by richard-hanxu** [stelzner/srt#5]
Thank you for your implementation. I was looking at the SRTEncoder class and I was wondering how the camera extrinsic/intrinsic matrices are incorporated into the input. I thought typical tensors representing intrinsic camera matrices could be [batch_size, num_images, 3, 3], and extrinsic camera matrices as [batch_size, num_images, 4, 4]. How is this incorporated into the new arguments for the encoder, camera_pos with size [batch_size, num_images, 3] and rays with [batch_size, num_images, height, width, 3]?

Thanks again.

**Comment by stelzner** [comment]
Hi! As defined in the paper in Eqs. 4 and 5, pose information is added to the input by concatenating encodings of camera position and viewing direction to every pixel of the image. This information is given by camera_pos and rays.

The camera matrices are used internally by the data loaders to compute this information. You can see how this happens for the NMR dataset [here](https://github.com/stelzner/osrt/blob/0eb6a004f4534b0c78bb84514cc660b179456cc7/osrt/data/nmr.py#L65). For Multishapenet, this job is done by the Sunds library.

**Comment by junkeun-yi** [comment]
Hello, just to add another question to this, how does the model handle inputs without pose information? It seems that the encoder components must take camera_pos and ray information to create a ray encoding for the transformer.

**Comment by stelzner** [comment]
Yes, I didn't experiment with unposed imagery. From what I understand, in their experiments with UpSRT, the authors simply didn't concatenate the pose information to the encoder input. So you would just skip [this step](https://github.com/stelzner/srt/blob/721ab9f917c4d3b056b2a80f76d3c9237e715365/srt/encoder.py#L88).

**Comment by junkeun-yi** [comment]
I see, thank you for the answer !
